- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Assume role
    community.aws.sts_assume_role:
      role_arn: "arn:aws:iam::603651671970:role/ReplatformPipelineBuildRole"
      role_session_name: "someRoleSession"
      region: "ap-south-1"
    register: assumed_role
  - debug:
      msg: "{{ assumed_role.sts_creds.access_key }}"
