- hosts: localhost
  tasks:
  - name: create a cloudformation stack
    amazon.aws.cloudformation:
      stack_name: "SampleWebAppCrossStack"
      state: "present"
      region: "ap-south-1"
      disable_rollback: true
      template: "SampleWebAppCrossStack.template"
      tags:
        Stack: "ansible-cloudformation"
