- hosts: localhost
  tasks:
  - name: create a cloudformation stack
    amazon.aws.cloudformation:
      stack_name: "SampleNetworkCrossStack"
      create_changeset: true
      state: "present"
      region: "ap-south-1"
      disable_rollback: true
      template: "new-code-pipeline2.yml"
      template_parameters:
        GitHubOwner: Santhosh
        GitHubOAuthToken: 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
        GitHubRepo: cfncross
      tags:
        Stack: "ansible-cloudformation-vpc"